### ISSUE TITLE
can't enter text using keyboard

### ISSUE THREAD

**Issue by marimes** [rgrizzell/lilygo-t-deck-keyboard#3]
I have a problem with my Lilygo T-Keyboard. When I got the device I installed the firmware (v2.5.5.e182ae7) and I could happily type on the keyboard. Then I connected through Bluetooth and used the device from the phone. Now I don't seem to be able to use the keyboard anymore. The only actions I can perform on the keyboard is Alt-B to activate the backlit keyboard and click any button to wake up the monitor. I cannot enter text.

**Comment by rgrizzell** [comment]
@marimes This repository is for the LILYGO T-Deck: https://www.lilygo.cc/products/t-deck

I'm not familiar with the version of firmware you mentioned. If you're looking for the official repository for the LILYGO T-Keyboard, its here: https://github.com/Xinyuan-LilyGO/T-keyboard/issues

If I've misunderstood, please let me know and I'll re-open this issue.
