### ISSUE TITLE
'b' character is sent at the same time when backlight is toggled with alt+b.

### ISSUE THREAD

**Issue by joyel24** [rgrizzell/lilygo-t-deck-keyboard#4]
Edit: Sorry, wrong repo I think...

**Comment by joyel24** [comment]
Sorry, wrong repo I think...

**Comment by rgrizzell** [comment]
If you're using the T-Deck, LILYGO's keyboard code is here: https://github.com/Xinyuan-LilyGO/T-Deck/blob/master/examples/Keyboard_T_Deck_Master/Keyboard_T_Deck_Master.ino

If you're using the standalone Bluetooth T-Keyboard, its here: https://github.com/Xinyuan-LilyGO/T-keyboard/blob/main/example/BLE_keybord/BLE_keybord.ino

**Comment by joyel24** [comment]
I know, that's why I closed it immediately.

You should rename your repository to prevent people from opening issues here.
Even about section is confusing.

Everything is confusing in your repo.

Only your nickname is not confusing with official repo...
